[project]
name = "hate-crack"
version = "2.0"
description = "Menu driven Python wrapper for hashcat"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.3.4",
    "requests>=2.31.0",
    "beautifulsoup4>=4.12.0",
    "ruff>=0.9.4",
]
